language: node_js
sudo: required
dist: trusty

node_js:
- stable

script:
- npm test

after_script:
- npm run test:coverage
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run demo:publish || false'
